"""Add pools and reply_to_step_id

Revision ID: c599418b16f4
Revises: 826f3e52edea
Create Date: 2026-08-01 23:50:44.589613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c599418b16f4'
down_revision: Union[str, None] = '826f3e52edea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('in_commenting_pool', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('accounts', sa.Column('in_reaction_pool', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('scenario_steps', sa.Column('reply_to_step_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'scenario_steps', 'scenario_steps', ['reply_to_step_id'], ['id'])
    op.alter_column('task_logs', 'account_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task_logs', 'account_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'scenario_steps', type_='foreignkey')
    op.drop_column('scenario_steps', 'reply_to_step_id')
    op.drop_column('accounts', 'in_reaction_pool')
    op.drop_column('accounts', 'in_commenting_pool')
    # ### end Alembic commands ###
